language: node_js
node_js:
- "8"

services:
  - docker
before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
script:
  - eval $(aws ecr get-login --region us-east-2)
  - docker-compose build
  - docker tag bitrac/web:latest 797028035271.dkr.ecr.us-east-2.amazonaws.com/bitrac/web:latest
  - docker push